// Revamped Proximity mines, courtesy from Brutal Hellfest!!
// Converted to ZS by DarynS. Blame me if something breaks.
Class PB_ThrownProxMine : Actor
{
    uint sinkTimer; // Submerged proximity mine will sink after the timer reaches a threshold.

    override void PostBeginPlay()
    {
        super.PostBeginPlay();
        sinkTimer = 0;
    }

    override void Tick()
    {
        super.Tick();
        if (isFrozen() || bDESTROYED) 
            return;

        // If we're underwater, count up until a threshold is reached.
        if (waterlevel > 1 && sinkTimer < 35)
            sinkTimer++;

        if (sinkTimer >= 35)
        {
            bBOUNCEONWALLS = false;
            bBOUNCEONCEILINGS = false;
            bBOUNCEONFLOORS = false;
            vel.z -= 1.0;
        }
    }

    Default
    {
        Radius 10;
        Height 10;
        Speed 15;
        Damage 0;
        Scale 0.35;
        SeeSound "MINE001";
        DeathSound "MINE002";
        
        Projectile;
        +BOUNCEONWALLS;
        +BOUNCEONCEILINGS;
        +BOUNCEONFLOORS;
        +BOUNCEAUTOOFF;
        BounceFactor 0.1;
        BounceCount 2;
        Gravity 1.1;
        
        Species "Marines";
        +DONTHARMSPECIES;
        +THRUSPECIES;

        -NOGRAVITY;
        +TELESTOMP;
        +THRUGHOST;
        +THRUACTORS;
        -NOTELEPORT;
        -BLOODSPLATTER;
        +CANNOTPUSH;
        +FORCERADIUSDMG;
        +FORCEXYBILLBOARD;
    }
	States
	{
        Spawn:
            XPFP A 1;
            TNT1 A 0 
			{
				bTHRUACTORS = false;
			}
            Loop;
        Death:
        XDeath:
            TNT1 A 0 A_SpawnItemEx("GroundProxMine", 0, 0, 0, 0, 0, 0, 0,SXF_NOCHECKPOSITION,0);
            Stop;
	}
}


Class PB_GroundProxMine : SwitchableDecoration
{
	Default
	{
		//$Title Proximity Mine
		//$Category Weapons
		//$Sprite "XPFPA0"
		Radius 10;
		Height 6;
		Damage 0;
		+SHOOTABLE;
		-SOLID;
		+NORADIUSDMG;
		+FLOORCLIP;
		+FRIENDLY;
		+FIXMAPTHINGPOS;
		+MOVEWITHSECTOR;
		+NOBLOOD;
		+NOICEDEATH;
		+DONTRIP;
		+THRUACTORS;
		+LOOKALLAROUND;
		+QUICKTORETALIATE;
		+FORCEXYBILLBOARD;
		+USESPECIAL;
		Activation THINGSPEC_Activate;
		Species "Marines";
		+MTHRUSPECIES;
		+THRUSPECIES;
		+DONTHARMCLASS;
		+DontHarmSpecies
		Mass 1000000;
		Health 10;
		Scale 0.35;
		PainChance "Kick", 255;
		PainChance "ExtremePunches", 255;
		damagefactor "Normal", 1.35;
		damagefactor "Melee", 99;
		damagefactor "Kick", 99;
		damagefactor "Avoid", 0.0;
		damagefactor "ExplosiveImpact", 0.0;
		damagefactor "Explosive", 0.0;
		damagefactor "Landmine", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "Blood", 0.0;	damagefactor "GreenBlood", 0.0;	damagefactor "BlueBlood", 0.0;	damagefactor "Taunt", 0.0;	damagefactor "KillMe", 0.0; damagefactor "Avoid", 0.0;  damagefactor "Taunt", 0.0;
		Damagetype "ExplosiveImpact";
	}
	States
	{
		Death.Kick:
		Death.ExtremePunches:
		Death.ExplosiveImpact:
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0; //A_Pain(;
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile("PB_ThrownProxMine", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;

		Active:
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("GreenFlareSpawn",0,6);
			XPFP A 6 Bright;
			TNT1 A 0 A_SpawnItem ("GreenFlareSpawn",0,6);
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			XPFP A 6 Bright;
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("GreenFlareSpawn",0,6);
			XPFP A 6 Bright;
			XPFP A 4 ;
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_ChangeFLag ("SHOOTABLE", 0);
			TNT1 A 0 A_SpawnItemEx ("PB_ProxMineAmmo",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0;
			Stop;

		DontTriggerOnFriendly:
			TNT1 A 0;
			TNT1 A 0 A_ClearTarget();
		Spawn:
			TNT1 A 0;
			XPFP A 10;
			TNT1 A 0 A_ChangeFlag ("SHOOTABLE",1);
			//TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XPFP AAA 8 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,6);
			XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
			Goto Spawn+2;
			
		
		Death:
			TNT1 A 0;	
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,9);
			XPFP A 4 Bright;
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,9);
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			XPFP A 4 Bright;
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,9);
			XPFP A 4 Bright;
			TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
			TNT1 A 0 A_SpawnItem ("RedFlareSpawn",0,9);
			XPFP A 4 Bright;
			
			EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
			TNT1 A 0 A_ChangeFlag ("FLOORCLIP", 0);
			TNT1 A 0 A_AlertMonsters();
			
			TNT1 A 0 A_PlaySound("Explosion",3);
			TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("MineExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_CustomMissile ("FireworkSFXType2", 0, 0, random (0, 360), 2, random (30, 60));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("MediumExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			//TNT1 A 0 A_SpawnItem("FragGrenadeExplosion");
			
			TNT1 A 0;
		
			TNT1 A 0 A_Explode(210,310, XF_HURTSOURCE);

			TNT1 A 0 A_Explode(190,170, XF_HURTSOURCE);

			TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	//		TNT1 A 0 A_SpawnItemEx ("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
	//		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BEXP B 0 BRIGHT A_Scream();
			TNT1 A 0 A_ALertMonsters();
			TNT1 AAA 0 A_CustomMissile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 0 A_Playsound("Explosion", 1);
			TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
			
			TNT1 A 0 A_JumpIf(GetCVar("pb_mineshrapnel") == 0, 21);
			TNT1 AAAAAAAAAA 0 A_CustomMissile ("PB_Shrapnel", 0, 0, random (0, 360), 2, random (-90, 90));
			TNT1 AAAAAAAAAA 0 A_CustomMissile ("PB_Shrapnel", 0, 0, random (0, 360), 2, random (-90, 90));
			
			TNT1 AAA 1 A_CustomMissile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0;
			TNT1 A 1 A_Stop();
			Stop;
		
	}
}
